id: P000323
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD90120
  title: ཝུན་ཁྲོན་རྫོང་གི་ས་ཆའི་མིང་བཏུས།
  author: ''
  volumes:
    675b356f46ce4d08b5370e4f257748bd:
      image_group_id: I1PD90135
      title: Volume 1 of wun khron rdzong gi sa cha'i ming btus
      volume_number: 1
      total_pages: 192
      base_file: v001.txt
ebook_metadata:
  title: ཝུན་ཁྲོན་རྫོང་གི་ས་ཆའི་མིང་བཏུས།
  author: ''
  sku: P000323
  cover: cover.jpg
  layers:
  - pagination
