id: I34409F77
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-12T16:57:59+00:00'
last_modified: '2022-06-10T04:07:37.457133+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD90120
  title: ཝུན་ཁྲོན་རྫོང་གི་ས་ཆའི་མིང་བཏུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    3B2A:
      image_group_id: I1PD90135
      title: Volume 1 of wun khron rdzong gi sa cha'i ming btus
      total_pages: 192
      order: 1
      base_file: 3B2A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
